version: "3"

services:
  bot:
    image: 888aaen/ruslan-bot
    volumes:
        - ./:/usr/src/app
    env_file: .env
    restart: always
  
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      WATCHTOWER_POLL_INTERVAL: 300